version: "3"

services:
  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - db-pg-volume:/var/lib/postgresql/data

  adminer:
    container_name: ${PROJECT_NAME}-adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
    ports:
      - 5588:8080

volumes:
  db-pg-volume:
